/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_study_jnilearn_HelloWorld */

#ifndef _Included_com_study_jnilearn_HelloWorld
#define _Included_com_study_jnilearn_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_study_jnilearn_HelloWorld
 * Method:    funInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_study_jnilearn_HelloWorld_funInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_study_jnilearn_HelloWorld
 * Method:    funStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_study_jnilearn_HelloWorld_funStr
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_study_jnilearn_HelloWorld
 * Method:    funBool
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_study_jnilearn_HelloWorld_funBool
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_study_jnilearn_HelloWorld
 * Method:    funIntArr
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_study_jnilearn_HelloWorld_funIntArr
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
